#!/usr/bin/env python3
"""Tests for scripts/friction-report.py.

Run with: python3 -m unittest discover tests
     or:  python3 tests/test_friction_report.py

The friction report is a read-only analyzer over the decisions Claude Code
persists in ~/.claude/projects/**/*.jsonl. These tests build synthetic
transcript files (attachment records + matching Bash tool_use blocks) and assert
the report's categorization, target extraction, and joins — never touching a real
transcript.

Signature fidelity: the reason fixtures are generated by calling
bash-foreground-guard.py's own finding builders (not hand-copied strings), so a
change to the guard's wording that broke a category regex fails these tests
instead of silently mis-bucketing real prompts.

Fixture rule (same as test_foreground_guard.py): synthetic commands only.
"""
import datetime as dt
import io
import json
import os
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from importlib import util
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "scripts" / "friction-report.py"
GUARD = REPO / "scripts" / "bash-foreground-guard.py"

# Filenames have dashes, so import by path.
_spec = util.spec_from_file_location("friction_report", SCRIPT)
fr = util.module_from_spec(_spec)
_spec.loader.exec_module(fr)

_gspec = util.spec_from_file_location("foreground_guard", GUARD)
guard = util.module_from_spec(_gspec)
_gspec.loader.exec_module(guard)


# Real reason strings, generated by the guard's own finding builders — one per
# category. Minimal cfg: finding_a reads only poll_action and hint.
_CFG = {'poll_action': 'ask', 'hint': ''}
REASON_WATCH = guard.finding_watch(
    _CFG, "gh run watch 456", "gh run watch",
    "check once with `gh run view <run-id>`")[1]
REASON_LOOP = guard.finding_loop(_CFG)[1]
REASON_SANDWICH = guard.finding_sandwich(_CFG)[1]
REASON_SLEEP = guard.finding_sleep(_CFG, 300)[1]
REASON_SLOW = guard.finding_slow(r"make test-race\b", 600000, 120000, False)[1]
# The deny->ask override prefix the hook prepends (see bash-foreground-guard.py
# main()); the underlying category must survive it.
REASON_OVERRIDE = ('foreground-guard override acknowledged '
                   '(FOREGROUND_GUARD_OVERRIDE is set) — downgraded from deny '
                   'to a confirmation prompt. ' + REASON_WATCH)


def _decision_record(tooluseid, command, stdout, cwd="/home/u/proj", ts=None,
                     hook_cmd='python3 "/x/scripts/bash-foreground-guard.py"'):
    """A transcript attachment record for one hook decision, plus the assistant
    tool_use record that command is joined from."""
    att = {
        "timestamp": ts or "2026-07-01T12:00:00Z",
        "cwd": cwd,
        "attachment": {
            "hookName": "PreToolUse:Bash",
            "command": hook_cmd,
            "toolUseID": tooluseid,
            "stdout": stdout,
        },
    }
    use = {
        "message": {"content": [
            {"type": "tool_use", "name": "Bash", "id": tooluseid,
             "input": {"command": command}}]},
    }
    return use, att


def _stdout(decision, reason):
    return json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": decision,
        "permissionDecisionReason": reason}})


def write_transcript(lines):
    """Write records (dicts) as a .jsonl transcript in a fresh temp dir; return
    the transcript root."""
    root = tempfile.mkdtemp(prefix="fg-guard-friction-")
    proj = os.path.join(root, "-home-u-proj")
    os.makedirs(proj)
    with open(os.path.join(proj, "session.jsonl"), "w", encoding="utf-8") as f:
        for rec in lines:
            f.write(json.dumps(rec) + "\n")
    return root


class ParseSinceTests(unittest.TestCase):
    def test_relative_units(self):
        now = dt.datetime.now(dt.timezone.utc)
        self.assertLess(fr.parse_since("7d"), now)
        self.assertAlmostEqual(
            (now - fr.parse_since("30m")).total_seconds(), 1800, delta=5)

    def test_absolute_date(self):
        self.assertEqual(fr.parse_since("2026-06-01").year, 2026)

    def test_bad_spec_exits(self):
        with self.assertRaises(SystemExit):
            fr.parse_since("banana")

    def test_empty_is_none(self):
        self.assertIsNone(fr.parse_since(None))


class GuardNameTests(unittest.TestCase):
    def test_strips_bash_prefix(self):
        self.assertEqual(
            fr.guard_name('python3 "/x/scripts/bash-foreground-guard.py"'),
            "foreground-guard")

    def test_sibling_guard(self):
        self.assertEqual(
            fr.guard_name('python3 "/x/bash-prod-guard.py"'),
            "prod-guard")

    def test_no_py_is_none(self):
        self.assertIsNone(fr.guard_name("gh run watch 1"))


class CategoryTests(unittest.TestCase):
    def test_each_builder(self):
        self.assertEqual(fr.category_of(REASON_WATCH), "watch")
        self.assertEqual(fr.category_of(REASON_LOOP), "loop-sleep")
        self.assertEqual(fr.category_of(REASON_SANDWICH), "sandwich")
        self.assertEqual(fr.category_of(REASON_SLEEP), "bare-sleep")
        self.assertEqual(fr.category_of(REASON_SLOW), "slow-timeout")

    def test_signatures_mutually_exclusive(self):
        # No fixture reason matches more than one category signature.
        reasons = [REASON_WATCH, REASON_LOOP, REASON_SANDWICH, REASON_SLEEP,
                   REASON_SLOW]
        for reason in reasons:
            hits = [c for c, rx in fr.CATEGORY_PATTERNS.items()
                    if rx.search(reason)]
            self.assertEqual(len(hits), 1, "%r matched %s" % (reason, hits))

    def test_every_category_has_a_hint(self):
        for cat in fr.CATEGORY_PATTERNS:
            self.assertIn(cat, fr.CATEGORY_HINT)

    def test_unmatched_is_other(self):
        self.assertEqual(fr.category_of("foreground-guard: something new"),
                         "other")

    def test_override_keeps_underlying_category(self):
        # The override prefix does not change the underlying category.
        self.assertEqual(fr.category_of(REASON_OVERRIDE), "watch")


class TargetExtractionTests(unittest.TestCase):
    def test_watch_names_the_command(self):
        self.assertEqual(fr.named_target(REASON_WATCH), "gh run watch 456")
        self.assertEqual(fr.tool_of(REASON_WATCH), "gh")

    def test_slow_names_the_pattern(self):
        self.assertEqual(fr.named_target(REASON_SLOW), r"make test-race\b")
        self.assertEqual(fr.tool_of(REASON_SLOW), "make")

    def test_template_categories_have_no_named_target(self):
        # loop/sandwich/bare-sleep lead with a generic template, not a command.
        for reason in (REASON_LOOP, REASON_SANDWICH, REASON_SLEEP):
            self.assertIsNone(fr.named_target(reason))
            self.assertIsNone(fr.tool_of(reason))


class BuildReportTests(unittest.TestCase):
    def _report(self, decisions):
        return fr.build_report(decisions)

    def test_outcomes_and_friction(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_SLEEP,
             "command": "sleep 300"},
            {"plugin": "foreground-guard", "decision": "defer", "reason": "",
             "command": "gh run view 456"},
        ])
        self.assertEqual(r["total"], 3)
        self.assertEqual(r["decisions"]["ask"], 2)
        self.assertEqual(r["decisions"]["defer"], 1)
        self.assertEqual(r["categories"]["watch"], 1)
        self.assertEqual(r["categories"]["bare-sleep"], 1)

    def test_named_target_and_tool_ranked(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_SLOW,
             "command": "make test-race"},
        ])
        self.assertEqual(r["targets"]["gh run watch 456"], 1)
        self.assertEqual(r["targets"][r"make test-race\b"], 1)
        self.assertEqual(r["tools"]["gh"], 1)
        self.assertEqual(r["tools"]["make"], 1)

    def test_template_category_has_no_target_but_ranks_command(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_LOOP,
             "command": "while true; do gh pr checks 1; sleep 5; done"},
        ])
        self.assertEqual(r["categories"]["loop-sleep"], 1)
        self.assertEqual(len(r["targets"]), 0)
        self.assertEqual(
            r["commands"]["while true; do gh pr checks 1; sleep 5; done"], 1)

    def test_override_counted(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_OVERRIDE,
             "command": "FOREGROUND_GUARD_OVERRIDE=x gh run watch 456"},
        ])
        self.assertEqual(r["overrides"], 1)
        self.assertEqual(r["decisions"]["ask"], 1)
        self.assertEqual(r["categories"]["watch"], 1)

    def test_joined_reason_hits_both_categories(self):
        joined = REASON_WATCH + " | " + REASON_SLEEP
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": joined,
             "command": "gh run watch 456; sleep 300"},
        ])
        self.assertEqual(r["categories"]["watch"], 1)
        self.assertEqual(r["categories"]["bare-sleep"], 1)


class IterDecisionsTests(unittest.TestCase):
    def test_join_and_filter(self):
        use1, att1 = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        # A prod-guard decision that must be excluded by --plugin foreground-guard.
        use2, att2 = _decision_record(
            "toolu_2", "kubectl delete ns x",
            _stdout("deny", "prod-guard: matches a production pattern ..."),
            hook_cmd='python3 "/x/bash-prod-guard.py"')
        root = write_transcript([use1, att1, use2, att2])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]

        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["decision"], "ask")
        self.assertEqual(got[0]["command"], "gh run watch 456")

        # --plugin all sees both.
        self.assertEqual(len(list(fr.iter_decisions(paths, "all", None, ""))), 2)

    def test_repo_filter(self):
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH),
            cwd="/home/u/gateway")
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", None, "gateway"))), 1)
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", None, "nope"))), 0)

    def test_cutoff_filter(self):
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH),
            ts="2020-01-01T00:00:00Z")
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        cutoff = dt.datetime(2025, 1, 1, tzinfo=dt.timezone.utc)
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", cutoff, ""))), 0)

    def test_defer_recorded_for_empty_stdout(self):
        # A silent (defer) decision is recorded with empty stdout.
        use, att = _decision_record("toolu_1", "gh run view 456", "")
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["decision"], "defer")

    def test_malformed_line_skipped(self):
        root = tempfile.mkdtemp(prefix="fg-guard-friction-bad-")
        with open(os.path.join(root, "s.jsonl"), "w", encoding="utf-8") as f:
            f.write("{not json\n")
            use, att = _decision_record(
                "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
            f.write(json.dumps(use) + "\n")
            f.write(json.dumps(att) + "\n")
        paths = [os.path.join(root, "s.jsonl")]
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", None, ""))), 1)


class PrintTests(unittest.TestCase):
    def test_empty(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(fr.build_report([]), 15)
        self.assertIn("No foreground-guard decisions", buf.getvalue())

    def test_sections_present(self):
        r = fr.build_report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15)
        out = buf.getvalue()
        self.assertIn("decisions analyzed: 1", out)
        self.assertIn("By category", out)
        self.assertIn("watch", out)
        self.assertIn("gh run watch 456", out)


class EndToEndTests(unittest.TestCase):
    def _run(self, root, *args):
        r = subprocess.run(
            [sys.executable, str(SCRIPT), "--transcripts", root,
             "--since", "all", *args],
            capture_output=True, text=True, timeout=30)
        self.assertEqual(r.returncode, 0, r.stderr)
        return r.stdout

    def test_text_report(self):
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        root = write_transcript([use, att])
        out = self._run(root)
        self.assertIn("foreground-guard decisions analyzed: 1", out)
        self.assertIn("watch", out)
        self.assertIn("gh run watch 456", out)

    def test_json_report(self):
        use, att = _decision_record(
            "toolu_1", "make test-race", _stdout("ask", REASON_SLOW))
        root = write_transcript([use, att])
        out = self._run(root, "--json")
        data = json.loads(out)
        self.assertEqual(data["total"], 1)
        self.assertEqual(data["decisions"]["ask"], 1)
        self.assertEqual(data["categories"]["slow-timeout"], 1)
        self.assertEqual(data["tools"]["make"], 1)

    def test_no_transcripts_errors(self):
        empty = tempfile.mkdtemp(prefix="fg-guard-friction-empty-")
        r = subprocess.run(
            [sys.executable, str(SCRIPT), "--transcripts", empty],
            capture_output=True, text=True, timeout=30)
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("No transcripts", r.stderr)


if __name__ == "__main__":
    unittest.main()
